name: CI

on: [push, pull_request]

jobs:
  ##############################################################################
  # macos (M1) with clang
  ##############################################################################
  macos-m1:
    name: macOS-M1, Clang (x3)

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: "Configure"
        run: |
          ./config/config.guess

          system_profiler SPHardwareDataType | grep Chip
          system_profiler SPHardwareDataType
