name: CI

on:
  pull_request:
  push:
    branches:
      - test

jobs:
  ##############################################################################
  # macos (x86) with clang and blas
  ##############################################################################
  macos-x86:
    name: macOS-x86 Clang with BLAS (x2)

    runs-on: macos-12

    env:
      FLINT_TEST_MULTIPLIER: "2"

    steps:
      - name: "Setup"
        run: |
          brew install make
          brew install autoconf
          brew install libtool
          brew install automake
          $(brew --prefix llvm@15)/bin/clang --version
          gmake --version
          autoconf --version
          echo "MAKE=gmake -j$(expr $(nproc) + 1) -l 10 --output-sync=target" >> $GITHUB_ENV

      - name: "Bla"
        run: |
          git clone --depth=1 https://github.com/ryepdx/gmp.git
          cd gmp
          ./.bootstrap
          ./configure \
            CC=$(brew --prefix llvm@15)/bin/clang \
            --disable-static
          sed -i '/(RM_TMP) tmp/d' mpn/Makeasm.am
          $MAKE
          cat mpn/tmp-sqr_basecase.s
